### PR TITLE
fix: only italicize cite closes #612

### LINKED ISSUE #596: Update blockquote to roman (no italic)
The large blue quote should be roman not italic. Only the attribute "Paul Rand" should be in italic.

Screen Shot 2019-12-02 at 10 17 01 AM

### LINKED ISSUE #612: Aside: update large blue quote. Attribute should not be italics. Only the publication titles should be italic
Screen Shot 2019-12-14 at 2 56 58 PM

### PR DESCRIPTION
**Pull request by vpicone**
preview link: https://gatsby-theme-carbon-git-fork-vpicone-block-quote-fix.carbon-design-system.now.sh/components/markdown#blockquotes-and-citations

- Removes italics
- adds hanging block quotes on desktop:
Screen Shot 2019-12-17 at 5 20 52 PM

- doesn't hang quotes on mobile:
Screen Shot 2019-12-17 at 5 16 51 PM

### CODE REVIEW

**Comment by alisonjoseph** [comment]
@vpicone Mike just opened #612 which seems related

**Comment by vpicone** [comment]
@mjabbink is this what you had in mind?

**Comment by mjabbink** [comment]
Should indent in mobile as well. Maybe 24 or 32px

**Comment by mjabbink** [comment]
Which will help with hanging quotes.

**Comment by mjabbink** [comment]
Ordered list needs live in mobile. Gets cropped and also doesn’t need to be flush right. I think Jeannie has specs for this

**Comment by vpicone** [comment]
@mjabbink @jeanservaas I'm not seeing the list crop, do you mind opening an issue with a screen shot?

**Pull request merged**
