### PR TITLE
This adds a 404 page that devs can populate with their own links

### PR DESCRIPTION
**Pull request by vpicone**
closes https://github.com/carbon-design-system/gatsby-theme-carbon/issues/91

How to implement the default 404:

1. Make a 404.js in your `src/pages` 
2. Import the 404 component from the theme
3. Export the component and provide your own links

```jsx
import React from 'react';
import { FourOhFour } from 'gatsby-theme-carbon';

const links = [
  { href: '/components/markdown', text: 'Markdown' },
  { href: '/components/Aside', text: 'Aside' },
  { href: '/components/demo', text: 'Demo' },
];

const Custom404 = () => <FourOhFour links={links} />;

export default Custom404;
```

### CODE REVIEW

**Comment by vpicone** [comment]
@shixiedesign the 404 can be viewed at gatsby-theme-carbon-git-fork-vpicone-404.carbon-design-system.now.sh/404

**Comment by alisonjoseph** [comment]
@shixiedesign I don't think @vpicone has even seen the alternate design, we were just porting over what we already had built to try and get it in for the teams with release dates of next week. 😅 

I'm seeing the text spacing jump also. weird.

**Comment by vpicone** [comment]
@alisonjoseph @shixiedesign I have some ideas for the patterned spec but haven't had a chance to give it a go. Wanted to get an mvp out for the pending releases.

I fixed the font loading jank.

**Comment by vpicone** [comment]
Changes from in person talk with @shixiedesign 
1) add 160px margin bottom to 404
2) match spec for mobile/tablet font size
3) padding should be 2rem left and right

**Pull request merged**
