### PR TITLE
fix: update right spacing for paragraphs and lists

### LINKED ISSUE #470: [mobile lists] text should not go into right margin
https://www.carbondesignsystem.com/guidelines/pictograms/contribute/

0FB770E4-942B-420E-8C1F-B3973401C7EB
B6CC8F0A-BA4F-44B0-A421-17B8D7AE5CF2

### LINKED ISSUE #503: body copy width too wide.
The length of body in many places seems to still go 100% full width of the 8 columns. It should never do this in any body copy situations.

Below are examples where body text goes all the way to the right edge of grid.

https://gatsby-theme-carbon.now.sh/getting-started
Screen Shot 2019-11-06 at 11 31 37 AM

https://gatsby-theme-carbon.now.sh/guides/configuration#global-search
Screen Shot 2019-11-06 at 11 34 09 AM

Screen Shot 2019-11-06 at 11 34 46 AM

Screen Shot 2019-11-06 at 11 35 11 AM

### LINKED ISSUE #582: Add 32px padding to right on paragraphs/lists
tablet and above (16px for mobile)

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #582
Closes #503 
Closes #470 

#### Changelog

**Changed**

- Updated paragraph and list spacing, 16px to the right at mobile, 32px at tablet and above

### CODE REVIEW

**Comment by alisonjoseph** [comment]
@sadek

**Comment by mjabbink** [comment]
good to go

**Comment by mjabbink** [comment]
good to go

**Comment by alisonjoseph** [comment]
Approved per Mike over slack

**Pull request merged**
