### PR TITLE
fix: links and buttons focus state

### LINKED ISSUE #773: Focus inconsistancies
- Next/prev missing focus styles
- edit in github link missing focus styles

We should take a sec to audit focus styles throughout the theme default elements.

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #773 

Several elements had either none or default-browser focus states: 

- page tabs
- anchor links 
- code snippet buttons (show more/link out buttons)
- edit this page link
- homepage callout links
- footer links (no focus at all!)
- next/previous button

Screen Shot 2020-06-01 at 2 48 48 PM
Screen Shot 2020-06-01 at 2 50 35 PM
Screen Shot 2020-06-01 at 2 46 42 PM
Screen Shot 2020-06-01 at 2 46 59 PM
Screen Shot 2020-06-01 at 2 47 22 PM
Screen Shot 2020-06-01 at 2 47 34 PM
Screen Shot 2020-06-01 at 4 22 07 PM
Screen Shot 2020-06-01 at 4 22 15 PM

**Testing**
- compare above mentioned items in this PR v. current Gatsby site.

### CODE REVIEW

**Comment by sstrubberg** [comment]
image

the focus on the footer appears to be stepping on the text a bit.

**Comment by sstrubberg** [comment]
image

Same with the text in the markdown

**Comment by sstrubberg** [comment]
Also, so happy we're working on this. I have an open issue on w3/design that speaks directly to the footer stuff.

**Comment by jnm2377** [comment]
@sstrubberg updated! 👍

**Comment by vpicone** [comment]
This is amazing! One small sort-of related thing I noticed while testing:

1. click search
2. press escape
3. The right side of the focus outline is missing. 

This feels like one of those problems that is either stupid easy or more difficult than it looks. If you could give it a shot here that would be awesome. If it gets weird we can open a separate issue.

**Comment by jnm2377** [comment]
@vpicone I'm not seeing the bug. Can you share a video or something of what you're seeing? 

This is what happens when I press esc.

search

**Comment by vpicone** [comment]
@jnm2377 hmm might be Firefox

**Comment by jnm2377** [comment]
@vpicone I've tried searching for answers on this since it's only happening on Firefox, but I haven't found any similar bugs. I tried a few different hacks like having a pseudo element, -moz-outline styles, overflow: hidden, but nothing is working. I have no idea what is happening with that. It's especially weird bc it definitely works when you tab into the button/click on it to open, so I don't know why it would cut off on esc.

**Comment by vpicone** [comment]
I’ll good, thanks for looking into it! It wasn’t introduced here so I’m okay merging

**Pull request merged**
