### PR TITLE
feat(MediumPosts): Component to automatically generate latest Medium posts on build time.

### PR DESCRIPTION
**Pull request by sstrubberg**
## MediumPosts component

**New**

- Component to automatically generate latest Medium posts on build time. Default posts is `3`, maximum is `10`. Uses the `<ArticleCard>` and has `light` (default) and `dark` themes.

### Configuration

https://gatsby-theme-carbon-git-fork-sstrubberg-feat-medium.carbon-design-system.now.sh/guides/configuration#medium

image

### Component docs

https://gatsby-theme-carbon-git-fork-sstrubberg-feat-medium.carbon-design-system.now.sh/components/MediumPosts

image

### CODE REVIEW

**Comment by sstrubberg** [comment]
> I have a maybe dumb question, why are the aspect ratios wrong on the last two images?
> 
> image

Not a dumb question at all. I was actually hoping for feedback on this issue because I was getting stuck. The issue is that all of the preview images from Medium are all different aspect ratios. I note the issue in the documentation, but I'm open to ideas on how to make it easier.

**Comment by mjabbink** [comment]
Can we see these in context of the page.

**Comment by jeanservaas** [comment]
@sstrubberg hmm, can we just show the aspect ratios we offer (1:1, 16:9) for our article card component? Even if medium has others, we don't really want to show them, because we'd never use allow use of our article cards that way.

@mjabbink click here on the preview link to see the content in context... he's put laid it out in markdown.

https://gatsby-theme-carbon-git-fork-sstrubberg-feat-medium.carbon-design-system.now.sh/components/MediumPosts/

**Comment by alisonjoseph** [comment]
Should the images be 16:9 aspect ratio? (thats what we have on the Carbon website for the article cards) @jeanservaas

**Comment by sstrubberg** [comment]
@alisonjoseph @jeanservaas I increased the height on xlg screens. I think that should align with a 16:9 aspect ratio.

image

**Comment by mjabbink** [comment]
@sstrubberg and @alisonjoseph 
The images should follow the aspect ration of IDL and what is in Carbon now. I believe it’s 16:9 or 1:2. @jeanservaas would know exact spec but I’m pretty certain it’s 16:9.

**Comment by jeanservaas** [comment]
Hey Scott the Gatsby theme ratio is 16:9 (that we're using in our article component on Carbon) -- it looks a little off in your preview now -- here's a side-by-side

image

**Comment by mjabbink** [comment]
Not just theme aspect ratio but one across IDL/Carbon system 😉

**Comment by jeanservaas** [comment]
yeah @mjabbink i just meant that we usually choose the 16:9 with our article component... other sites like / design use the 1:1 with the article component... i think you could also use the 1:2 aspect ratio too... but just to keep things simple for scott, let's use the 16:9 here as our article card default.

**Comment by mjabbink** [comment]
gotcha.

**Pull request merged**
