### PR TITLE
fix: adjust search container width to align with page contents

### LINKED ISSUE #1101: Search field is too wide on desktop
This [PR](https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1050) updated the search styles to stretch across and is correct. Currently however the search is stretching too far to the left. 

What it should look like
Screen Shot 2021-02-25 at 8 06 07 AM

### PR DESCRIPTION
**Pull request by vpicone**
closes #1101 

Adds some media queries to handle search width at various viewports.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
The calculations seem off by a bit on my 13 inch MacBook fullscreen. 🤔 

Screen Shot 2021-03-16 at 8 56 08 PM

**Comment by mjabbink** [comment]
Preview looks good in both desktop and mobile

**Comment by vpicone** [comment]
@jeanservaas made it so we only expand to 100% when the left nav is hidden. Once we get out of tablet range, it maxes out at the original spec/component implementation.

**Comment by mjabbink** [comment]
Preview looks wrong now? What happened?

**Comment by mjabbink** [comment]
MOBILE CORRECT
Screen Shot 2021-03-23 at 1 29 08 PM

**Comment by mjabbink** [comment]
TABLET CORRECT
Screen Shot 2021-03-23 at 1 28 41 PM

**Comment by mjabbink** [comment]
DESKTOP — Needs to be to one of the green lines. I believe the space was for the far left one.

Screen Shot 2021-03-23 at 1 30 58 PM

**Comment by mjabbink** [comment]
Also seeing this in the preview for “Workplace Design” — https://ibm-brand.github.io/workplace-xg/


Screen Shot 2021-03-23 at 1 58 10 PM

**Comment by vpicone** [comment]
@mjabbink @aagonzales and @jeanservaas okayed returning to the original search spec on desktop. 

Because the shell sits above and separate from the page contents, justifying to that content requires hacky approximations at each viewport with unpleasant edge cases (see @alisonjoseph screenshot)

**Comment by vpicone** [comment]
Reason why it requires hacks: the page container pushes from the left and the search emerges from the right. 

We also need to subtract the switcher menu which gets spicy.

**Comment by vpicone** [comment]
> Also seeing this in the preview for “Workplace Design” — https://ibm-brand.github.io/workplace-xg/
> 
> 
> 
> 
> 
> Screen Shot 2021-03-23 at 1 58 10 PM
> 
> 

Its a theme issue so they'll get a fix once we ship this and they update.

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Comment by mjabbink** [comment]
In the last image the search is spanning too far.

**Comment by mjabbink** [comment]
@vpicone @alisonjoseph This seems to have reverted because it’s the same as before the issue was made.

**Pull request merged**
