### PR TITLE
Webinar

### PR DESCRIPTION
**Pull request by vpicone**

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Can we embed tweets in mdx deck?
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🎉 TFW you finally finish refactoring your website to <a href="https://twitter.com/gatsbyjs?ref_src=twsrc%5Etfw">@gatsbyjs</a> and now it’s blazing fast! 🤩 <a href="https://t.co/0et1WJDJkT">https://t.co/0et1WJDJkT</a> 🔥 <a href="https://t.co/RncZ5KJl4y">pic.twitter.com/RncZ5KJl4y</a></p>&mdash; Carbon Design System (@_carbondesign) <a href="https://twitter.com/_carbondesign/status/1047622438757048320?ref_src=twsrc%5Etfw">October 3, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Screen Shot 2019-07-22 at 7 33 13 PM

**Comment by vpicone** [comment]
@alisonjoseph lol idk if the gif will work but I'm sure there's a way

Using this URL to track the progress: https://gatsby-theme-carbon-webinar.now.sh/

**Comment by alisonjoseph** [comment]
### Add links at the end
https://github.com/carbon-design-system/gatsby-theme-carbon
https://gatsby-theme-carbon.now.sh
https://www.carbondesignsystem.com/

### Showcase links
IBM Design AI - https://www.ibm.com/design/ai/
IBM Design Language site - https://www.ibm.com/design/language/
IBM Design Research site - expected to launch the beginning of August
Carbon Design System - move to theme is in progress
IBM Brand internal site, and other various business units internal sites

**Comment by alisonjoseph** [comment]
Add more info around pain points in beginning slides
Add slide to show poll
Add shadowing slide

**Pull request merged**
