### PR TITLE
fix: caption spacing inside tab

### LINKED ISSUE #1493: [Image caption] Add captions under each tab image
## Detailed description
There are a couple of issues identified:

1. Captions: We need to add individual captions under each tab image. When a caption is placed inside a tab, there is a missing 1rem top padding above the caption.
2. Background Display: The white background observed is the tab container itself, not a background on the image. As a result, anything inside the tab will display on that white background.

While we could build a custom solution to remove the white background, the current implementation is functioning as intended, aside from the missing 1rem top padding.

image

## Possible solution 
(@alisonjoseph mentioned -)
To address these issues, we need to enhance the Gatsby tabs component. A potential solution could involve creating a new tab type, such as `<Tab type="image">`, allowing us to style this variant differently to remove the background and adjust padding as needed.

## Additional information
- [Related issue](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1488)
- Ref: [Thread](https://ibm-studios.slack.com/archives/GSCEH4RSP/p1715693675697239?thread_ts=1715688078.860809&cid=GSCEH4RSP)

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #1493

#### Changelog
- add correct top margin above captions

## Testing
Check captions on Tabs and Captions page. Should have 1rem top margin.

### CODE REVIEW

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Hi Alison! 
Will the caption appear within the image, meaning will the caption have the same white background as the image? 🤔

image

--- 

(This is what I’m looking at 👇🏻, I hope that’s correct)

image

**Comment by alisonjoseph** [comment]
@Kritvi-bhatia17 the white background is coming from the Tabs component, not the image. The caption is within the tab, so it will appear on the white background. The only thing this PR is doing is adding the correct spacing above the caption that was missing when it was used inside of the Tabs component.

**Review by ariellalgilmore — APPROVED** [review]

**Comment by Kritvi-bhatia17** [comment]
Oh, got it, Alison. Thanks a lot for the detailed explanation! 
In that case, I’ll just confirm with the other designers as well and will get back to you.

**Comment by Kritvi-bhatia17** [comment]
Hi @alisonjoseph, I discussed with the team, and it seems a bit inconsistent with other images where the caption appears below the image. 
Initially, I thought adding captions for the tab images would improve consistency, but given the current solution, it might look a bit odd and cause confusion, especially with images (shown below) that already include text. It could become unclear which is the caption and which is part of the artwork. 
Sorry about this and thanks for working on the issue! I just wanted to explore the possibility of adding captions for the tab images below them.

image

**Pull request closed without merging**
