### PR TITLE
fix: feedback button colors

### LINKED ISSUE #886: Feedback button: Make them the same gray color.
currently the feedback button is different color than the jump to top of page button. They should be the same.

—

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #886 

**Changed**

- closed state launch btn now matches `BackToTop` btn color
- expanded state background color now matches closed state hover color
- added a white box-shadow to `BackToTop` btn focus state to match feedback launch btn focus state

**Removed**
- filled face icon for launch btn

### CODE REVIEW

**Comment by jeanservaas** [comment]
@jnm2377 

Girl, thank you for being patient on this one. I am so sorry for running you around! I had forgotten how tricky the interactive colors were on these circles because they need to work on light and dark elements.

After talking about the other specs I gave you earlier with @mjabbink we realized that the white selected state didn't work so well for smiley. So I did a little more exploration in context and this is what we came up with:

### New interactive color specs for back to top and feedback buttons

image


## In context looks @mjabbink 

**Back to top button on the homepage**

enabled:

image

hover:

image


**Feedback button and back to top on interior pages**

enabled:

image

hover:

image

selected:

image

**Review by sstrubberg — CHANGES_REQUESTED** [review]
I noticed that you didn't use color tokens in some spots. Can we introduce those? This will effect things when we drop theme'ing

**Comment by jnm2377** [comment]
@sstrubberg all of the colors are color tokens. Or do you mean css variables?

**Comment by jnm2377** [comment]
@jeanservaas updated

**Review by sstrubberg — APPROVED** [review]

**Review by vpicone — APPROVED** [review]

**Pull request merged**
