### PR TITLE
style: removed the padding -closes #1074

### LINKED ISSUE #1074: Content & code snippet in list should go to the right margin
————

### PR DESCRIPTION
**Pull request by sstrubberg**
Closes #1074

### CODE REVIEW

**Comment by sstrubberg** [comment]
@mjabbink is this what you're wanting? Your spec wasn't clear on what it needed to look like for md and lg screens.

**Comment by mjabbink** [comment]
Looks right to me. Those images (text and snippet) in issue were meant to illustrate that they needed to go to the right margin versus being cut short. Looks like you resolved that and unfortunately I forgot to paste in the link where I screen grabbed those.

**Review by vpicone — COMMENTED** [review]
I think we only want to make this tweak on mobile right?

**Comment by mjabbink** [comment]
Hmm. In desktop something looks off as well. The right side of list items should not exceed the typical 8 column width for the main body spans across. It should also not get padding on the right side. So only left side is getting indented as the list needs to with bullets, numbers letters, etc but the content always spans to the same right edge of the margin same as NON list body copy. Hope this makes sense.

I the sample I pointed out in the issue the content was getting extra padding on the right so it was spanning to the right edge.

In desktop (images below) I can’t tell if the snippet containers is too short or if the text is what is going too long?
https://gatsby-theme-carbon-git-issue1074.carbon-design-system.vercel.app/getting-started

Screen Shot 2020-12-16 at 3 15 22 PM


———

**Comment by mjabbink** [comment]
Just double checked. The above has the text going beyond the 8 columns and the image above that has the snippet going beyond the 8 columns. This means something wonky is going on.

**Review by jnm2377 — APPROVED** [review]

**Comment by jnm2377** [comment]
Hmm.. maybe we should get specs for the list if there are more issues with it.. I thought this issue was just about padding but seems like there are more things wrong with list alignment/width/etc.

**Comment by sstrubberg** [comment]
Left a comment on the original issue regarding the specs.

**Comment by sstrubberg** [comment]
Went ahead and did Vince's suggestion. I need feedback plz.

**Comment by sstrubberg** [comment]
turned out the code snippets were in the lists, which is not a pattern we normally do. I just pulled them out and manually made the ordered list.

**Pull request merged**
