### PR TITLE
docs: fix typo in npm-scripts.mdx

### PR DESCRIPTION
**Pull request by kai687**
The word _Sites_ at the beginning should be plural, and not _Site's_.

### CODE REVIEW

**Comment by sstrubberg** [comment]
Good catch. Resolve the merge conflicts and we're good to go!

**Review by sstrubberg — CHANGES_REQUESTED** [review]
fix merge conflicts

**Review by sstrubberg — APPROVED** [review]

**Comment by kai687** [comment]
Sorry, I don't understand how to fix the commit message. *Just* `git commit --amend` with the correct message and then pushing again to this branch?

**Review by vpicone — APPROVED** [review]

**Comment by vpicone** [comment]
🚀 thanks!

**Pull request merged**
