### PR TITLE
feat: update switcher content

### LINKED ISSUE #984: Switcher —> Update Content with labels
Need to update switcher—  “Digital” under Design disciplines should link to http://ibm-dotcom-library.mybluemix.net/

FYI @wonilsuhibm

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #984 

- the margin for the dividers is already `32px` (attaching a picture at the bottom) so I didn't change it
- updates the labels/order of sections

**reviewers** 
- please double check the link url's. There wasn't anything in the issue about the urls, so if something is wrong pls link the correct url and I'll update it.

Screen Shot 2020-10-07 at 3 00 30 PM

### CODE REVIEW

**Comment by vpicone** [comment]
@jeanservaas @janchild I'll defer are we moving forward with this structure?

**Comment by jnm2377** [comment]
@vpicone seems like @mjabbink said yes: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/984#issuecomment-704572868

**Review by vpicone — APPROVED** [review]

**Review by jeanservaas — COMMENTED** [review]
@jnm2377 Sorry that the links weren't included in the issue.

The only change is that we want the IBM Design link (with the lock next to it) under Community to link to the internal W3 IBM Design site, not the external one. That's why we put that lock there because it is behind a login. I will be right back with the link to that site and add it here. 

here we go:
w3.ibm.com/design

**Comment by jnm2377** [comment]
@jeanservaas updated the design link. What about the brand center link? That one also has a lock on it. But it's a public link. Is that right?

**Comment by vpicone** [comment]
@jnm2377 this is out of scope, but I just noticed the Switcher toggle button is doing a weird pulse when clicked could you see if it might be an easy add on here?

**Review by sstrubberg — APPROVED** [review]

**Comment by sstrubberg** [comment]
> @jeanservaas updated the design link. What about the brand center link? That one also has a lock on it. But it's a public link. Is that right?

It's public, but it's tucked behind IBMid. If you don't have an IBMid account, you won't be able to access the site.

**Comment by mjabbink** [comment]
@jeanservaas @janchild I also think moving Community to the bottom makes more sense to me.

**Comment by mjabbink** [comment]
Also noting the change to `Carbon for IBM.com` here already: http://ibm-dotcom-library.mybluemix.net/

**Comment by jnm2377** [comment]
@mjabbink @jeanservaas updated!

**Comment by jeanservaas** [comment]
@jnm2377 Sorry for the delay, we were shopping a few things around. This is the new, final order... per Mike's comment, we moved community now to the bottom

image

**Comment by mjabbink** [comment]
@jeanservaas and @jnm2377 The above image is not correct —> “IBM.com Library” should be “Carbon for IBM.com”

**Comment by mjabbink** [comment]
@jnm2377 Were you able to address this bug https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1023#issuecomment-706434845 in this issue?

**Comment by jnm2377** [comment]
@mjabbink I went by this comment https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1023#issuecomment-707326717 You can see the changes in the deployed preview

**Comment by jnm2377** [comment]
Is your preview not updating? bc it doesn't say IBM.com Library anymore

**Comment by jeanservaas** [comment]
@jnm2377 

lord, don't hate me, one more change. We need to put IBM iX back into "Practices" at the moment. Not everyone was cool with removing it and I don't want it to hold us up.

**Here is the link that goes with iX:**
https://www.ibm.com/services/ibmix/

image

**Comment by mjabbink** [comment]
@jnm2377 I see the updates other than the last from Jeannie. All good other than that one.

**Comment by jeanservaas** [comment]
@jnm2377 I am so sorry for all this confusion. Some updates were made to the original issue about the IBM.com library name change that I missed because I was only looking here. 

Apparently, now that they've changed their name, we're moving forward with it in the app switcher:

This is the final verified by @mjabbink and @janchild 

I am updating it the issue too. 

**The links for iX is:**
https://www.ibm.com/services/ibmix/

The link for Carbon for IBM.com is:


image

**Comment by mjabbink** [comment]
@jnm2377 @jeanservaas Looking good. Only need to add iX back into Practices.

**Comment by jnm2377** [comment]
@jeanservaas @mjabbink added back iX, should be available to review after the new preview finishes building 👍

**Comment by janchild** [comment]
@jnm2377 This is looking good. One thing I noticed is that the URL for Carbon for IBM.com is using the redirect. Their new URL is `https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/`

It doesn't matter because they do have a redirect, but just thought I'd mention in case you wanted to put the new URL in instead.

**Comment by jnm2377** [comment]
@janchild thanks! just updated the link 👍

**Review by janchild — APPROVED** [review]
This looks great to me, @jnm2377!  Thanks so much for your patience. These kinds of things always take a lot of back and forth, but it will be so worthwhile. These changes will make a huge difference for everyone using the switcher. 🥂

**Comment by mjabbink** [comment]
Looks great @jnm2377

**Review by jeanservaas — APPROVED** [review]
BOOM

**Pull request merged**
