### PR TITLE
fix: properly align Footer and NextPrevious with content

### LINKED ISSUE #72: Footer and PageHeader alignment issues
There are some alignment bugs occurring around some core components. Notably the PageHeader and Footer components.

### PageHeader 
The title text is different than the IDL implementation

54e69a00-7826-11e9-82b2-fc20a1c71f00

### Footer
Looks to be some padding issues in relation to the content

Screen Shot 2019-05-17 at 11 35 57 AM

### PR DESCRIPTION
**Pull request by vpicone**
Closes #72

### CODE REVIEW

**Comment by alisonjoseph** [comment]
I think Page header was already fixed. 

image

**Comment by alisonjoseph** [comment]
The last footer column needs `bx--offset-lg-2`  so it is aligned correctly.

**Comment by vpicone** [comment]
@alisonjoseph this adjusts the height and margin of the PageHeader to match the DL site, since it was the most common target. We can implement the override on Carbon's end once we migrate to the theme.

I added the offset and fixed the footer column. I'm gonna make an issue to migrate the css-in-js stuff over to sass modules when I we have some spare time.

**Comment by alisonjoseph** [comment]
so close, the borders need a space on the right edge on mobile
Screen Shot 2019-05-24 at 10 25 57 AM
, right now they are flush with the edge of the browser

**Pull request merged**
