### PR TITLE
feat: add ArtDirection component

### PR DESCRIPTION
**Pull request by vpicone**

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Not sure about the name "ArtDirection", but otherwise love the simplicity here

**Comment by vpicone** [comment]
@emyarod Yeah, otherwise you might end up duplicating the middle one to hit two media queries or something silly like that.

**Comment by alisonjoseph** [comment]
If someone puts only two images the first will show at mobile, and the second at tablet and above, correct?

**Comment by vpicone** [comment]
@alisonjoseph art direction is the [actual name](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#Art_direction) for the thing we're doing here.

I considered more vague names (e.g. Image, Picture, ImageComponent, Images, ResponsiveImages), but they all imply that there is something _other_ than art direction happening.

**Comment by vpicone** [comment]
@alisonjoseph yeah that's correct. I updated the documentation to explain more clearly:

>You can place up to three images inside of the ArtDirection component. The first will be used for mobile, the second for tablet, and the third for desktop. If only two images are provided, the second image will be used for both tablet and desktop.

**Pull request merged**
