### PR TITLE
fix: update list alignment styles

### LINKED ISSUE #392: number list hanging outside body copy
@jeanservaas 

- [ ]  Numbers need to be inside the body copy column span. Desktop and mobile.

IMG_4212

.

Screen Shot 2019-08-30 at 3 23 14 PM

### PR DESCRIPTION
**Pull request by alisonjoseph**
closes #392 

> Numbers need to be inside the body copy column span

- Lists now align inside the body copy and don't hang 1/2 way in the gutter.
- Adds extra spacing for two digit numbers 
- updated demo to include more ordered list items

### CODE REVIEW

**Comment by jnm2377** [comment]
I'm seeing some weird spacing. I've cleared my cache, but not sure why the styles are off. Is anyone else seeing this?
Screen Shot 2019-09-06 at 2 28 25 PM

**Comment by alisonjoseph** [comment]
@jnm2377 I'm seeing it too in the demo url, but not locally. weird.

**Comment by jnm2377** [comment]
@alisonjoseph 👍  just want to make sure this is what I'm supposed to be seeing:
Screen Shot 2019-09-09 at 10 32 11 AM

**Comment by alisonjoseph** [comment]
Yep!

**Pull request merged**
