### PR TITLE
feat(ResourceCard): add a blue background variation

### PR DESCRIPTION
**Pull request by sstrubberg**
Updated the ResourceCard component to include a blue60 background with a blue70 hover.

### CODE REVIEW

**Comment by sstrubberg** [comment]
Made some styles for disabled and soften the top blue border.

image

We are currently using it as a way to draw out a "main" call to action.

image

We experimented with using the `dark` option, but that gave us an almost "disabled" feeling when we used it.

**Comment by jeanservaas** [comment]
@sstrubberg 

Apologize for the delay, I just saw this. The blue looks very aggressive, especially in the light theme and it's a color that's usually reserved for our buttons, not our resource cards, which are more akin to links. 

I'm wondering 1) why this card needs emphasis and 2)  if you can try some other exploration if you need emphasis here. Maybe scale rather than color. We've actually been exploring some smaller resource tiles for certain situations we've encountered on Carbon. But I don't think we're ready to move forward with this as a variation yet.

**Comment by sstrubberg** [comment]
> @sstrubberg
> 
> Apologize for the delay, I just saw this. The blue looks very aggressive, especially in the light theme and it's a color that's usually reserved for our buttons, not our resource cards, which are more akin to links.
> 
> I'm wondering 1) why this card needs emphasis and 2) if you can try some other exploration if you need emphasis here. Maybe scale rather than color. We've actually been exploring some smaller resource tiles for certain situations we've encountered on Carbon. But I don't think we're ready to move forward with this as a variation yet.

Thanks for the feedback @jeanservaas. We want to draw emphasis to the card because we have a block of four cards with various links to resources. We want to elevate one of the four cards as our main call-to-action and we felt like the blue60 was doing a pretty solid job compared to the dark mode tile that is currently in the theme. We'll do some exploring into how we might elevate the CTA without relying on the blue. We'll also do some testing with users to see if the blue comes off as too aggressive.

**Comment by mjabbink** [comment]
No blue resource cards please

**Pull request closed without merging**
