### PR TITLE
Use color tokens in FourOhFour styles

### LINKED ISSUE #1309: 404 page unreadable
## Detailed description

The 404 page seems to be broken in the v3 releases of the Carbon theme- it has dark text on a dark background making it completely unreadable, except for the large colourful 404.

For example, see https://merative.github.io/spm-ui-addon-devenv/underview

Previous releases of the theme seem to work ok.

For example, see https://merative.github.io/acd-containers/about/underview/

## Additional information

I was able to work around the issue by shadowing the `FourOhFour` component and providing a fixed them to `Layout`

https://github.com/jt-nti/cicsdev.github.io/commit/8d2e6b0f9c27e9f7e2a15d93f0a3b57b7f2d4bf4#diff-c344e11cd21f5403a22a6256b9fd1d7c9455cc8972ba55d98531d14332e26703R14

I think updating the `FourOhFour` component to pass the `interiorTheme` to `Layout` might be part of the solution, although I suspect some additional style changes might also be necessary.

### PR DESCRIPTION
**Pull request by jt-nti**
Closes #1309

Use correct tokens in 404 page theme

#### Changelog

**Changed**

- FourOhFour.module.scss

### CODE REVIEW

**Comment by eng618** [comment]
Hey @jt-nti any update on this?

**Comment by jt-nti** [comment]
Hi @eng618, sorry I'd forgotten about this. The PR checks are failing and I didn't hear back from @alisonjoseph on issue #1309 so it's kind of in limbo I think. If I get a chance, I'll rebase the PR, set it to ready and see what happens.

**Comment by jt-nti** [comment]
The PR checks are still failing but that looks like it's something `yarn install` related rather than the style changes.

**Review by eng618 — APPROVED** [review]

**Comment by eng618** [comment]
Looks good in the preview 

image

**Comment by eng618** [comment]
@jt-nti thanks for the contribution. I set up auto-merge, so once everything passes this should merge!

**Pull request merged**
