### PR TITLE
fix(global search): 1989-aat-avt1-gs-about-carbon-aria-expanded

### PR DESCRIPTION
**Pull request by andreancardona**
Closes carbon website issue found in Gatsby theme: https://github.com/carbon-design-system/carbon-website/issues/1989

Removed` aria-expanded` causing accessibility issue -  since it's mainly only used on buttons (per convo with D.A.)

- [ ] Run test locally on home page and make sure following error does not show up
Screen Shot 2020-11-17 at 10 47 28 PM

### CODE REVIEW

**Review by vpicone — COMMENTED** [review]
Rather than removing it, maybe we move it to the button? https://www.w3.org/TR/wai-aria-practices-1.1/#wai-aria-roles-states-and-properties-14

**Comment by andreancardona** [comment]
Oops just. seeing this comment will make a changee today!

**Comment by andreancardona** [comment]
@vpicone updated!

**Review by sstrubberg — COMMENTED** [review]
image

I don't see the error you are reporting anymore, but I do see two new errors.

**Review by sstrubberg — APPROVED** [review]
LGTM!

**Review by vpicone — APPROVED** [review]

**Pull request merged**
