### PR TITLE
(docs): 851-FED-video-getting-started-docs

### LINKED ISSUE #851: Add Andrea's FED talk to getting started docs
Whenever it gets published

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #851

### CODE REVIEW

**Comment by vpicone** [comment]
@jeanservaas can we add a gray-20 border to this video so it doesn't blend with the background? @andreancardona we can just wrap it with a a `<div style={{border: '1px solid e0e0e0'}}>`

### before
after

### after
Screenshot_2020-07-08 Getting started

**Comment by jeanservaas** [comment]
Yes we're doing that in usage images too, but for that situation, do a Gray 30, 1px bkg.

you'll see the precedent for it on this page. Color guidelines

image

**Comment by sstrubberg** [comment]
@andreancardona what if you just changed the color of that opening title screen to like any other color?

**Comment by andreancardona** [comment]
@sstrubberg transferred over to IBM Design Vimeo :) 

@vpicone added border per @jeanservaas 's design requests. 

Ready for review.

**Pull request merged**
