### PR TITLE
fix: Update width of next/prev component, resolves #569

### LINKED ISSUE #569: Next/Prev alignment
The Next/Prev text isn't on the grid, as shown in the picture.

Screen Shot 2019-11-26 at 7 52 33 AM

### PR DESCRIPTION
**Pull request by xxxle0**
Closes #569

+ need to add width and update max-width of .link-container in Next/Prev component

#### Changelog

**New**

- width: 99%

**Changed**

- max-width: 98rem;

### CODE REVIEW

**Comment by vpicone** [comment]
This seems like we're just kind of nudging it, can you elaborate on how you came to these values?

Adding `width: 99%` across the board seems kind of arbitrary.

**Comment by vpicone** [comment]
@xxxle0 I pushed a fix using a different strategy, let me know if this works for you.

**Comment by xxxle0** [comment]
i think your solution is better. Thanks. Btw, What is your tool to measure component in the picture? @vpicone

**Comment by vpicone** [comment]
@xxxle0 thats the “inspect element” tool in Firefox dev tools.

**Comment by xxxle0** [comment]
Thanks 👍

**Pull request merged**
