### PR TITLE
docs: code blocks docs page

### PR DESCRIPTION
**Pull request by alisonjoseph**

### CODE REVIEW

**Comment by muditjuneja** [comment]
Hi @alisonjoseph what exactly are you referring to here? If you intend to see same behaviour within a nested code block just like you did, I don't think that would work. hideCode prop will only work on parent and as you have set the value to `false` in the parent, you are seeing a "Show More" button which would not be visible if you pass the value as `true`

**Comment by muditjuneja** [comment]
I see what is happening. There should not be a Show More button here. Let me debug this.
Screenshot 2024-03-14 at 1 53 36 AM

**Comment by muditjuneja** [comment]
Hey @alisonjoseph can you take a look at this PR- https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1444/files

hideCode prop value is coming as a string field which is truthy always.

**Comment by alisonjoseph** [comment]
@muditjuneja pulled your fix into this PR, thank you! 👍

**Comment by alisonjoseph** [comment]
@eng618 have you just been manually doing releases for next on npm, wasn't sure if there was anything automated set up. I wanted to start testing the release next week against the Carbon website.

**Review by eng618 — APPROVED** [review]
Looks great!

**Comment by eng618** [comment]
> @eng618 have you just been manually doing releases for next on npm, wasn't sure if there was anything automated set up. I wanted to start testing the release next week against the Carbon website.

Hey @alisonjoseph yeah, I have just been manually pushing the next releases... I'll push an update after this one gets in. It's only automated for the **main** branch

**Comment by alisonjoseph** [comment]
@eng618 awesome thanks. Anything specific I might run into while upgrading the Carbon site? I was going to try and take notes and add things to the migration doc as I went as well. Feel free to message over on Discord too if thats easier.

**Comment by eng618** [comment]
Messaged on discord

**Pull request merged**
