### PR TITLE
fix: align Footer component columns to match CarbonDesign site and IDL styles

### LINKED ISSUE #72: Footer and PageHeader alignment issues
There are some alignment bugs occurring around some core components. Notably the PageHeader and Footer components.

### PageHeader 
The title text is different than the IDL implementation

54e69a00-7826-11e9-82b2-fc20a1c71f00

### Footer
Looks to be some padding issues in relation to the content

Screen Shot 2019-05-17 at 11 35 57 AM

### PR DESCRIPTION
**Pull request by SilverFox70**
closes #72

### CODE REVIEW

**Comment by vpicone** [comment]
Great! Thanks for the PR.

**Comment by vpicone** [comment]
I'm still having some issues on mobile :/
Screen Shot 2019-05-23 at 7 36 52 AM

**Comment by alisonjoseph** [comment]
I believe the footer background color should actually be black, not gray. Unless this changed somewhere that I missed @vpicone ?

**Comment by vpicone** [comment]
Going to close this in favor of https://github.com/carbon-design-system/gatsby-theme-carbon/pull/97 since this doesn't address the PageHeader alignment issue in #72 and we need to also fix the mobile view

**Pull request closed without merging**
