### PR TITLE
fix(page-tabs): nav aria unique labels

### PR DESCRIPTION
**Pull request by andreancardona**
Closes issue found on carbon website - from theme: 

- https://github.com/carbon-design-system/carbon-website/issues/1554
-  https://github.com/carbon-design-system/carbon-website/issues/1716

**Changed**
Added. unique aria labels for tabs

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]

**Comment by vpicone** [comment]
I'm not sure the `currentTab` makes for a good label. It's not like an ID or key where we just need it to be unique. For instance [here](https://gatsby-theme-carbon-git-1716-avt1-tabs-multiple-nav-roles.carbon-design-system.vercel.app/guides/navigation/sidebar) the navigation is named `sidebar`. If you change the tab (to tabs) then the label changes to just `tabs`.

I wonder if using parent would be more appropriate so the label stays the same for that nav element between tabs (probably Navigation)

**Comment by andreancardona** [comment]
> I'm not sure the `currentTab` makes for a good label. It's not like an ID or key where we just need it to be unique. For instance [here](https://gatsby-theme-carbon-git-1716-avt1-tabs-multiple-nav-roles.carbon-design-system.vercel.app/guides/navigation/sidebar) the navigation is named `sidebar`. If you change the tab (to tabs) then the label changes to just `tabs`.
> 
> I wonder if using parent would be more appropriate so the label stays the same for that nav element between tabs (probably Navigation)

okay! so changing this to `aria-label="navigation"` am I understanding that corrrectly? @vpicone

**Comment by vpicone** [comment]
@andreancardona sorry it's kinda confusing/meta with these pages haha. 

As a different example, the label here would be color: https://www.carbondesignsystem.com/guidelines/color/overview/

(Not overview, usage and code)

**Comment by andreancardona** [comment]
> @andreancardona sorry it's kinda confusing/meta with these pages haha.
> 
> As a different example, the label here would be color: https://www.carbondesignsystem.com/guidelines/color/overview/
> 
> (Not overview, usage and code)

ahh makes a lot more sense just pushed. up a fix @vpicone

**Review by vpicone — APPROVED** [review]

**Pull request merged**
