### PR TITLE
fix: 943-audit-avt1-homepage-banner-role

### LINKED ISSUE #943: audit-avt1-homepage: more than one banner role
This is an issue being copied over from Carbon Website Accessibility Audit: https://github.com/carbon-design-system/carbon-website/issues/1409

## Environment:

> Operating system: Mac
> Browser: Chrome 
> AVT :one:
> Page: [Homepage](https://www.carbondesignsystem.com/)

## Detailed Description: 

There is more than one element with "banner" role on the page.

## What to do: 
Remove "banner" role from all but one element. (The<header> element has an implicit role of banner when it is a descendent of the body element.)

## Why is this important?
When more than one "banner" landmark role is used on a web page, it can confuse people who use assistive technologies that rely on this information to easily navigate the various sections in the page.

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #943

### CODE REVIEW

**Comment by vpicone** [comment]
@andreancardona did this resolve DAP issue? Hopefully without out creating new ones haha.

**Comment by andreancardona** [comment]
> @andreancardona did this resolve DAP issue? Hopefully without out creating new ones haha.

@vpicone @jnm2377 Looks like it did! :) 

Screen Shot 2020-07-27 at 11 08 20 AM

**Comment by jnm2377** [comment]
If you click on the main section when the sidenav is open, there's like a focus outline on part of it. Is it meant to do that?

Screen Shot 2020-07-27 at 12 06 50 PM

**Comment by andreancardona** [comment]
> If you click on the main section when the sidenav is open, there's like a focus outline on part of it. Is it meant to do that?
> 
> Screen Shot 2020-07-27 at 12 06 50 PM

@jnm2377 from what I can tell that's what it currently does / that is the current behavior - I'm not sure though 🤷‍♀️

**Comment by jnm2377** [comment]
ahhh gotcha @andreancardona  hmm.. I'm not sure we want a focus outline... but since it's an existing issue, I'm fine with merging :)

**Pull request merged**
