### PR TITLE
fix(lists): correct right margin in nested lists

### LINKED ISSUE #832: Nested list margin to great on right.
## Detailed description

> Describe in detail the issue you’re having.

When having a nested list inside, the right migin is huge.

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected the margin-right to match that of the parent list, and only have additional margin-right to signify the nest.

> What browser are you working in?

Chrome

## Steps to reproduce the issue

1. Create a mdx page
1. Create a nested list

    ```
    1. Quidem facilis veritatis.

        1. Reiciendis rerum dolorem tempore. Et molestiae ullam animi deserunt itaque in dolore. Nostrum et reprehenderit magni mollitia facilis voluptates et. Qui ratione consectetur rerum.

        2. Accusamus quod sunt reprehenderit sed fugit architecto dolor consequatur repellat.

    2. Et tenetur amet ut sed. Voluptatem sint perferendis nesciunt rerum sed sapiente eius et. Ratione blanditiis aut aut cupiditate assumenda culpa molestiae aut. Veritatis ad ut est dolorem fugiat ut eius. Et in doloremque excepturi dolorem veritatis velit voluptatem. Quo quisquam voluptates sequi.
    ```

1. inspect page in browser to see large margins on the nested list.

## Additional information

- Screenshots or code

image

- Notes

on latest version `"gatsby-theme-carbon": "^1.24.1",`

### PR DESCRIPTION
**Pull request by ENG618**
Closes #832 

Corrects right margin of nested lists, and adds examples in **spacing-audit.mdx**

#### Changelog

**New**

**Changed**

- fix right margin of nested lists
- fix mismatched AnchorLink in **spacing-audit.mdx**
- add section to **spacing-audit.mdx** for verification
- fix broken link in FeedbackDialog.mdx

**Removed**

### CODE REVIEW

**Comment by ENG618** [comment]
See [test/spacing-audit/#code-and-nested-lists](https://gatsby-theme-carbon-4owho4bof.vercel.app/test/spacing-audit/#code-and-nested-lists)

**Comment by vpicone** [comment]
Awesome! Thank you for this. Do we know where that margin was coming from in the first place?

**Comment by ENG618** [comment]
my understanding is this list 

```scss
.Markdown-module--list--oZv7L {
    width: 66.667%;
}
```

Seems to basically be doubling it when the list is nested...

**Comment by ENG618** [comment]
I'm gonna push another nested list fix:

**before**:
image

**after**:
image

There are probably some other components that have issues rendering in lists at well but these are the ones I have used and found.

**Comment by mjabbink** [comment]
The issue we’re having is the indented images. They don’t necessarily have to indent. That is the problem we have with the IDL Isometric page. The images are indenting and becoming scaled down. They just need to stay the original scale and fit in the grid the same as the images above it.


———
The images below do not need to scale and should be in the grid



https://www.ibm.com/design/language/illustration/isometric-style/production#drawing-a-cylinder
———

Screen Shot 2020-06-16 at 1 29 01 PM

**Comment by vpicone** [comment]
@mjabbink that's a diff issue, will need to be tackled in a diff PR.

**Comment by mjabbink** [comment]
The right side should all align. All content stays within original 8 column span

**Comment by ENG618** [comment]
@vpicone there is a slight difference in the 1st notification (which is only in a row) and the second 2 (that are in a list and nested list).  This is as close as it gets without reworking how rows and everything else works.

image

**Pull request merged**
